FoodBlog/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FoodBlog.Models
{
    public class Recipe
    {
        [Key]
        public int RecipeID { get; set; }

        public string Name { get; set; }

        public int CheffID { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime PublishDate { get; set; }

        public string CreationProcess { get; set; }

        public virtual Cheff Cheff { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
    }

    public class GroupByCheffModel
    {
        public int CheffID { get; set; }
        public string CheffName { get; set; }
        public int TotalRecipes { get; set; }
    }
}

FoodBlog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodBlog.DAL;
using FoodBlog.Models;

namespace FoodBlog.Controllers
{
    public class CommentsController : Controller
    {
        private ProjectContext db = new ProjectContext();


        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Recipe);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        [Authorize(Users = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Add(int RecipeID)
        {
            
            var newComment = new Comment();
            newComment.RecipeID = RecipeID; // this will be sent from the ArticleDetails View, hold on :).

            return PartialView(newComment);
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "CommentID,RecipeID,Title,AuthorName,AuthorSiteURL,Content")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return Json(new { succeeded = true, commentData = comment });
                //return Json(comment, JsonRequestBehavior.AllowGet);
                //return PartialView(comment);

            }

            ViewBag.RecipeID = new SelectList(db.Recipes, "RecipeID", "Title", comment.RecipeID);
            return Json(new { succeeded = false });
            //return PartialView(comment);

        }


        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.RecipeID = new SelectList(db.Recipes, "RecipeID", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentID,RecipeID,Title,AuthorName,AuthorSiteURL,Content")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RecipeID = new SelectList(db.Recipes, "RecipeID", "Title", comment.RecipeID);
            return View(comment);
        }

        // GET: Comments/Edit/5
        [Authorize(Users = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.RecipeID = new SelectList(db.Recipes, "RecipeID", "Title", comment.RecipeID);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult Edit([Bind(Include = "CommentID,RecipeID,Title,AuthorName,AuthorSiteURL,Content")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RecipeID = new SelectList(db.Recipes, "RecipeID", "Title", comment.RecipeID);
            return View(comment);
        }

        // GET: Comments/Delete/5
        [Authorize(Users = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FoodBlog/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodBlog.DAL;
using FoodBlog.Models;

namespace FoodBlog.Controllers
{
    public class RecipesController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: Recipes
        public ActionResult Index()
        {
            return View(db.Recipes.ToList());
        }

        // GET: Recipes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }

            // Incerment the counter for this cheff
            int cheffId = recipe.Cheff.ID;
            string currCheffName = db.Cheffs.First(c => c.ID == cheffId).Name;
            Dictionary<string, int> counterDictionary = (Dictionary<string, int>)Session["counterDictionary"];
            if (counterDictionary is null)
            {
                counterDictionary = new Dictionary<string, int>();
            }
            if (counterDictionary.ContainsKey(currCheffName))
            {
                counterDictionary[currCheffName]++;
            }
            else
            {
                counterDictionary.Add(currCheffName, 1);
            }
            Session["counterDictionary"] = counterDictionary;

            return View(recipe);
        }

        // GET: Recipes/Create
        public ActionResult Create()
        {
            var allCheffs = db.Cheffs;
            this.ViewData["cheffsSelectable"] = (IEnumerable<FoodBlog.Models.Cheff>)allCheffs;
            return View();
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecipeID,Name,CheffID,PublishDate, CreationProcess")] Recipe recipe)
        {
            recipe.PublishDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Recipes.Add(recipe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var allCheffs = db.Cheffs;
            this.ViewData["cheffsSelectable"] = (IEnumerable<FoodBlog.Models.Cheff>)allCheffs;
            return View(recipe);
        }

        // GET: Recipes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }

            var allCheffs = db.Cheffs;
            this.ViewData["cheffsSelectable"] = (IEnumerable<FoodBlog.Models.Cheff>)allCheffs;
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult Edit([Bind(Include = "RecipeID,Name,CheffID,PublishDate,CheffNickName,CreationProcess")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recipe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var allCheffs = db.Cheffs;
            this.ViewData["cheffsSelectable"] = (IEnumerable<FoodBlog.Models.Cheff>)allCheffs;
            return View(recipe);
        }

        // GET: Recipes/Delete/5
        [Authorize(Users = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe recipe = db.Recipes.Find(id);
            db.Recipes.Remove(recipe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Recipes
        public ActionResult Filter(string placeOfBirthInput, string CheffName, string CheffNickName, string RecipeName)
        {
            var results = db.Recipes.AsQueryable();
            Country placeOfBirth;
            if (!string.IsNullOrEmpty(CheffNickName))
            {
                results = from recipe in db.Recipes
                          join cheff in db.Cheffs on recipe.RecipeID equals cheff.ID
                          where cheff.NickName == CheffNickName
                          select recipe;
            }
            if (!string.IsNullOrEmpty(placeOfBirthInput) && Enum.TryParse(placeOfBirthInput, out placeOfBirth))
            {
                results = results.Where(c => c.Cheff.PlaceOfBirth == placeOfBirth);
            }
            if (!string.IsNullOrEmpty(CheffName))
            {
                results = results.Where(c => c.Cheff.Name == CheffName);
            }

            if (!string.IsNullOrEmpty(RecipeName))
            {
                results = results.Where(c => c.Name == RecipeName);
            }
            
            return View("Index", results.ToList());
        }

        public ActionResult GroupByCheff()
        {
            // Group by and join
            var totalRecipes = from recipe in db.Recipes
                             group recipe by recipe.CheffID into g
                             join cheff in db.Cheffs on g.Key equals cheff.ID
                             select new GroupByCheffModel() { CheffName = cheff.Name, TotalRecipes = g.Sum(p => 1) };

            return View(totalRecipes.ToList());
        }

        [HttpGet]
        public ActionResult GroupByCheffData()
        {
            // Group by and join
            var totalRecipes = from recipe in db.Recipes
                             group recipe by recipe.CheffID into g
                             join cheff in db.Cheffs on g.Key equals cheff.ID
                             select new GroupByCheffModel() { CheffName = cheff.Name, TotalRecipes = g.Sum(p => 1) };

            return Json(totalRecipes.ToList(), JsonRequestBehavior.AllowGet);
        }

        // Get Recipes/WantMore
        [HttpPost]
        public ActionResult WantMore(string cheffId, string currentRecipeId)
        {
            try
            {
                int recipeId = Int32.Parse(currentRecipeId);
                int chId = Int32.Parse(cheffId);
                var alikeRecipe = (from recipe in db.Recipes
                                 where recipe.RecipeID != recipeId && recipe.CheffID == chId
                                 select recipe.RecipeID).SingleOrDefault();
                if (alikeRecipe != 0)
                {
                    return Json(new Dictionary<string, object> { { "url", "/Recipes/Details/" + alikeRecipe } });
                }
                else
                {
                    return Json(new Dictionary<string, object> { { "error", "didnt found any" } });
                }
            }
            catch (Exception ex)
            {
                return Json(new Dictionary<string, object> { { "error", ex.Message } });
            }


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FoodBlog/Views/Recipes/Create.cshtml
@model FoodBlog.Models.Recipe

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="display-in-row">
                <label class = "control-label col-md-2">Cheff</label>
                @Html.DropDownList("CheffID",
                    new SelectList((IEnumerable<FoodBlog.Models.Cheff>)ViewData["cheffsSelectable"], "ID", "Name"), new { @class = "btn btn-default" })


                @Html.ValidationMessageFor(model => model.Cheff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="display-in-row">
                @Html.LabelFor(model => model.CreationProcess, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreationProcess, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreationProcess, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FoodBlog/Views/Recipes/Delete.cshtml
@model FoodBlog.Models.Recipe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete the Recipe?</h3>
<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Recipe Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Cheff Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cheff.Name)
        </dd>

        <dt>
            Publish Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishDate)
        </dd>

        <dt>
            Creation Process
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationProcess)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FoodBlog/Views/Recipes/Details.cshtml
@model FoodBlog.Models.Recipe
@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    $(document).ready(function () {
        var token = $('[name=__RequestVerificationToken]').val();
		var bodyData = {
			cheffId: "@Model.Cheff.ID",
            currentRecipeId: "@Model.RecipeID"
        };
        bodyData['__RequestVerificationToken'] = token;
        $.ajax({
            url: "/Recipes/WantMore",
            type: "Recipe",
            data: bodyData,
            success: function (response) {
                var el = document.getElementById("moreRecipes");

                if (!response.error) {
                    el.href = response.url;
                }
                else {
                    el.parentElement.removeChild(el);
                }
            },
            error: function (res) {
                console.log('err', res)
            }
        });

    });
</script>

@{
    ViewBag.Title = "Details";
}

<div class="blog-post">
    <p class="blog-post-title">@Html.DisplayFor(model => model.Name) </p>

    <div class="blog-post-meta">@Html.DisplayFor(model => model.PublishDate)</div>
    <p>@Html.DisplayFor(model => model.CreationProcess)</p>
      
</div>

<div class="container">
    <h3>Comments:</h3>    
    <ul class="comments-list col-md-8" id="comment-list">@Html.DisplayFor(model => model.Comments)</ul>
</div>
<div class="add-comment">
    @Html.Action("Add", "Comments", new { RecipeID = Model.RecipeID })


</div>
<hr>
<div class="container">    
    @Html.ActionLink("Back to List", "Index")
</div>

FoodBlog/Views/Recipes/Edit.cshtml
@model FoodBlog.Models.Recipe

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RecipeID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cheff, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CheffID",
                    new SelectList((IEnumerable<FoodBlog.Models.Cheff>)ViewData["cheffsSelectable"], "ID", "Name"), new { @class = "btn btn-default" })

                @Html.ValidationMessageFor(model => model.Cheff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationProcess, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationProcess, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationProcess, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FoodBlog/Views/Recipes/GroupByCheff.cshtml
@model IEnumerable<FoodBlog.Models.GroupByCheffModel>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/d3")
<head>
    <style>
        .axis {
            font: 10px sans-serif;
        }

        .bar {
            fill: #98abc5;
        }

            .bar:hover {
                fill: gray;
            }

        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }
    </style>
</head>
<script type="text/javascript">
    $(document).ready(function () {
        var svg = d3.select("svg"),
            margin = { top: 20, right: 20, bottom: 30, left: 40 },
            width = +svg.attr("width") - margin.left - margin.right,
            height = +svg.attr("height") - margin.top - margin.bottom;

        var x = d3.scaleBand().rangeRound([0, width]).padding(0.1),
            y = d3.scaleLinear().rangeRound([height, 0]);

        var g = svg.append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        d3.json("/Recipes/GroupByCheffData", function (data) {
            x.domain(data.map(function (d) { return d.CheffName; }));
            y.domain([0, d3.max(data, function (d) { return d.TotalRecipes; })]);

            g.append("g")
                .attr("class", "axis axis--x")
                .attr("transform", "translate(0," + height + ")")
                .call(d3.axisBottom(x));

            g.append("g")
                .attr("class", "axis axis--y")
                .call(d3.axisLeft(y).ticks(d3.max(data, function (d) { return d.TotalRecipes; })))
                .append("text")
                .attr("transform", "rotate(-90)")
                .attr("y", 6)
                .attr("dy", "0.71em")
                .attr("text-anchor", "end")
                .text("Frequency");

            g.selectAll(".bar")
                .data(data)
                .enter().append("rect")
                .attr("class", "bar")                
                .attr("x", function (d) { return x(d.CheffName); })
                .attr("y", function (d) { return y(d.TotalRecipes); })
                .attr("width", x.bandwidth())
                .attr("height", function (d) { return height - y(d.TotalRecipes); });

        })

    })
</script>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CheffName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalRecipes)
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CheffName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalRecipes)
            </td>
        </tr>
    }
</table>
<br />
<u><b>Statistics:</b></u>
<br />
<svg width="480" height="250"></svg>

FoodBlog/Views/Recipes/Index.cshtml
@model IEnumerable<FoodBlog.Models.Recipe>

<canvas id="myCanvas" width="300" height="70"></canvas>
<div id="multicolumns" class="mul-col-blue container text-center">

    <section id="videoContainer">
        <!-- Introduction -->
        <video width="400" controls>
            <source src="~/Media/videos/videoplayback.mp4" type="video/mp4">
        </video>
    </section>    
</div>


<script>
    const size = 500;
    var c = document.getElementById("myCanvas");
    var ctx = c.getContext("2d");
    ctx.font = "50px cursive";
    ctx.strokeText("Recipes", 20, 40);    
</script>


<div class="container">
    <div class="container row">
        <div class="list-inline buttons">
            @using (Html.BeginForm("GroupByCheff", "Recipes"))
            {
                <input class="btn btn-lg btn-stats" type="submit" value="Recipes By Cheff" />
                <p class="btn btn-lg btn-add-blog" href="#" role="button">@Html.ActionLink("Add Recipe", "Create", null, new { @style = "color: darkseagreen;" })</p>
            }
        </div>
    </div>
    @{
        Dictionary<string, int> counterDictionary = (Dictionary<string, int>)Session["counterDictionary"];
        if (counterDictionary != null)
        {
            string favCheffName = counterDictionary.FirstOrDefault(x => x.Value == counterDictionary.Values.Max()).Key;
            <div class="alert alert-success">Like @Html.Raw(favCheffName)? @Html.ActionLink("click", "Filter", new { CheffName = favCheffName }) for more</div>
        }
    }

    @using (Html.BeginForm("Filter", "Recipes", FormMethod.Post, new { @class = "form-inline" }))
    {
        <h3>Filter Recipes by</h3>
    
        <div class="form-group">
            @Html.TextBox("CheffName", "", new { @class = "form-control", placeholder = "Cheff Name" })
            @Html.TextBox("CheffNickName", "", new { @class = "form-control", placeholder = "Cheff Nick Name" })
            @Html.TextBox("RecipeName", "", new { @class = "form-control", placeholder = "Recipe Name" })
            <center>
                <input class="btn btn-search-recipes" style="text-align:center;margin-top:10px;" type="submit" value="Search" />
            </center>
        </div>
        
    }

    <hr />

</div>


<hr />


@foreach (var item in Model)
{
    <div class="blog-post">
        <p class="blog-post-title">@Html.ActionLink(item.Name + " - " + item.Cheff.Name, "Details", new { id = item.RecipeID }, new { @style = "text-decoration:none; color: black;" }) </p>

        <div class="blog-post-meta">@Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.PublishDate))</div>
        <p>@Html.DisplayFor(modelItem => item.CreationProcess)</p>
        
        @{ if (Request.IsAuthenticated)
            {
                <div>
                    @Html.ActionLink("Edit", "Edit", new { id = item.RecipeID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.RecipeID })
                </div>
            }
        }
    </div>
}