FoodBlog/Models/Cheff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FoodBlog.Models
{

    public enum Country { France, GreatBritain, USA, Israel, India };

    public class Cheff
    {
        

        [Key]
        public int ID { get; set; }

        public string Name { get; set; }

        public string NickName { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime BirthDay { get; set; }

        public Country PlaceOfBirth { get; set; }
    }
}

FoodBlog/Controllers/CheffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodBlog.DAL;
using FoodBlog.Models;

namespace FoodBlog.Controllers
{
    public class CheffsController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: Cheffs
        public ActionResult Index(string CheffName, string CheffNickName, string placeOfBirthInput)
        {
            var results = db.Cheffs.AsQueryable();
            
            Country placeOFBirth;//

            if (!string.IsNullOrEmpty(CheffName))
            {
                // query join between cheffs and recipes
                results = from cheff in db.Cheffs
                          where cheff.Name == CheffName
                          select cheff;//,Name,CheffID,Name,NickName;
            }


            // recipe query by either last name or either first name
            if (!string.IsNullOrEmpty(CheffNickName))
            {
                // query join between cheffs and recipes
                results = from cheff in db.Cheffs
                          where cheff.NickName == CheffNickName 
                          select cheff;//,Name,CheffID,Name,NickName;
            }


            if (!string.IsNullOrEmpty(placeOfBirthInput) && Enum.TryParse(placeOfBirthInput, out placeOFBirth))
            {
                results = results.Where(s => s.PlaceOfBirth == placeOFBirth);
            }
            

            return View(results.ToList());
        }

        // GET: Cheffs
        [HttpGet]
        public ActionResult IndexData(string CheffName, string CheffNickName, string placeOfBirthInput)
        {
            var chefss = db.Cheffs.ToList();

            return Json(chefss, JsonRequestBehavior.AllowGet);
        }

        // GET: Cheffs/Details/5
        [Authorize(Users = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cheff cheff = db.Cheffs.Find(id);
            if (cheff == null)
            {
                return HttpNotFound();
            }
            return View(cheff);
        }

        // GET: Cheffs/Create
        [Authorize(Users = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cheffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult Create([Bind(Include = "ID,Name,NickName,BirthDay,PlaceOfBirth")] Cheff cheff)
        {
            if (ModelState.IsValid)
            {
                db.Cheffs.Add(cheff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cheff);
        }

        // GET: Cheffs/Edit/5
        [Authorize(Users = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cheff cheff = db.Cheffs.Find(id);
            if (cheff == null)
            {
                return HttpNotFound();
            }
            return View(cheff);
        }

        // POST: Cheffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult Edit([Bind(Include = "ID,Name,NickName,BirthDay,PlaceOfBirth")] Cheff cheff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cheff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cheff);
        }

        // GET: Cheffs/Delete/5
        [Authorize(Users = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cheff cheff = db.Cheffs.Find(id);
            if (cheff == null)
            {
                return HttpNotFound();
            }
            return View(cheff);
        }

        // POST: Cheffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Cheff cheff = db.Cheffs.Find(id);
            db.Cheffs.Remove(cheff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FoodBlog/Views/Cheffs/Create.cshtml
@model FoodBlog.Models.Cheff

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Cheff</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.BirthDay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthDay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BirthDay, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PlaceOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlaceOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlaceOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FoodBlog/Views/Cheffs/Delete.cshtml
@model FoodBlog.Models.Cheff

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cheff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceOfBirth)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FoodBlog/Views/Cheffs/Details.cshtml
@model FoodBlog.Models.Cheff

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h3>Cheff</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceOfBirth)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FoodBlog/Views/Cheffs/Edit.cshtml
@model FoodBlog.Models.Cheff

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cheff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FoodBlog/Views/Cheffs/Index.cshtml
@model IEnumerable<FoodBlog.Models.Cheff>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/d3")

<head>
    <style>
        .arc text {
            font: 10px sans-serif;
            text-anchor: middle;
        }

        .arc path {
            stroke: #fff;
        }
    </style>
</head>

<script type="text/javascript">
    $(document).ready(function () {
        var svg = d3.select("svg"),
            width = +svg.attr("width"),
            height = +svg.attr("height"),
            radius = Math.min(width, height) / 2,
            g = svg.append("g").attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");

        var color = d3.scaleOrdinal(["#98abc5", "#8a89a6", "#7b6888", "#6b486b", "#a05d56", "#d0743c", "#ff8c00"]);

        var pie = d3.pie()
            .sort(null)
            .value(function (d) { return d.value; });

        var path = d3.arc()
            .outerRadius(radius - 10)
            .innerRadius(0);

        var label = d3.arc()
            .outerRadius(radius - 40)
            .innerRadius(radius - 40);

        var BirthPlaces = ["France", "GreatBritain", "USA", "Israel", "India"];

        d3.json("/Cheffs/IndexData", function (data) {
            var groupByPlaceOfBirth = {};

            data.forEach(function (d) {
                groupByPlaceOfBirth[d.PlaceOfBirth] = (groupByPlaceOfBirth[d.PlaceOfBirth] || 0) + 1;
            });

            var revisedData = Object.keys(groupByPlaceOfBirth).map(function (d) { return { value: groupByPlaceOfBirth[d], role: BirthPlaces[d] } });

            var arc = g.selectAll(".arc")
                .data(pie(revisedData))
                .enter().append("g")
                .attr("class", "arc");

            arc.append("path")
                .attr("d", path)
                .attr("fill", function (d) { return color(d.value); });

            arc.append("text")
                .attr("transform", function (d) { return "translate(" + label.centroid(d) + ")"; })
                .attr("dy", "0.35em")
                .text(function (d) { return d.data.role; });
        })
    })
</script>

@{
    ViewBag.Title = "Index";
}

@{
    if (Request.IsAuthenticated)
    {
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    }
}


<div class="container">
    @using (Html.BeginForm("Index", "Cheffs", FormMethod.Post, new { @class = "form-inline" }))
    {
        <h3>Filter Cheffs by</h3>
        <div class="form-group">
            @Html.TextBox("CheffName", "", new { @class = "form-control", placeholder = "Name" })
        </div>
        <div class="form-group">
            @Html.DropDownList("placeOfBirthInput", EnumHelper.GetSelectList(typeof(FoodBlog.Models.Country)), "Country", new { @class = "form-control" })
        </div>
        <input class="btn btn-search-posts" type="submit" value="Search" />
    }

</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NickName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlaceOfBirth)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NickName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaceOfBirth)
            </td>
            @{
                if (Request.IsAuthenticated)
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                }
            }
        </tr>
    }

</table>

<br />
<b><u>Entire Statistics:</u></b>
<br />
<svg width="480" height="250"></svg>